export const CARDS = [
  { id: 1, value: 'A', flipped: false, matched: false },
  { id: 2, value: 'B', flipped: false, matched: false },
  { id: 3, value: 'C', flipped: false, matched: false },
  { id: 4, value: 'D', flipped: false, matched: false },
  { id: 5, value: 'E', flipped: false, matched: false },
  { id: 6, value: 'F', flipped: false, matched: false },
  { id: 7, value: 'G', flipped: false, matched: false },
  { id: 8, value: 'H', flipped: false, matched: false },
  { id: 9, value: 'A', flipped: false, matched: false },
  { id: 10, value: 'B', flipped: false, matched: false },
  { id: 11, value: 'C', flipped: false, matched: false },
  { id: 12, value: 'D', flipped: false, matched: false },
  { id: 13, value: 'E', flipped: false, matched: false },
  { id: 14, value: 'F', flipped: false, matched: false },
  { id: 15, value: 'G', flipped: false, matched: false },
  { id: 16, value: 'H', flipped: false, matched: false },
  { id: 17, value: 'I', flipped: false, matched: false },
  { id: 18, value: 'I', flipped: false, matched: false },
  // { id: 19, value: 'J', flipped: false, matched: false },
  // { id: 20, value: 'J', flipped: false, matched: false },
];
